#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Paste
Version  : 3.0.7
Release  : 51
URL      : https://files.pythonhosted.org/packages/70/ad/ebba105ebdac9319ae48695b6faedb946b0bdc2bf0035366690b8ba18250/Paste-3.0.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/70/ad/ebba105ebdac9319ae48695b6faedb946b0bdc2bf0035366690b8ba18250/Paste-3.0.7.tar.gz
Summary  : Tools for using a Web Server Gateway Interface stack
Group    : Development/Tools
License  : MIT
Requires: Paste-license = %{version}-%{release}
Requires: Paste-python = %{version}-%{release}
Requires: Paste-python3 = %{version}-%{release}
Requires: python-openid
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : pytest-runner
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
*Paste is in maintenance mode and recently moved from bitbucket to github.
Patches are accepted to keep it on life support, but for the most part, please
consider using other options.*

%package license
Summary: license components for the Paste package.
Group: Default

%description license
license components for the Paste package.


%package python
Summary: python components for the Paste package.
Group: Default
Requires: Paste-python3 = %{version}-%{release}
Provides: paste-python

%description python
python components for the Paste package.


%package python3
Summary: python3 components for the Paste package.
Group: Default
Requires: python3-core

%description python3
python3 components for the Paste package.


%prep
%setup -q -n Paste-3.0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551399890
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Paste
cp docs/license.txt %{buildroot}/usr/share/package-licenses/Paste/docs_license.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Paste/docs_license.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
