#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Paste
Version  : 3.2.2
Release  : 56
URL      : https://files.pythonhosted.org/packages/d3/24/e4089e949efd47fdb91c3341b1e034e2182c8d22f80d017c23988e48e9c0/Paste-3.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/d3/24/e4089e949efd47fdb91c3341b1e034e2182c8d22f80d017c23988e48e9c0/Paste-3.2.2.tar.gz
Summary  : Tools for using a Web Server Gateway Interface stack
Group    : Development/Tools
License  : MIT
Requires: Paste-license = %{version}-%{release}
Requires: Paste-python = %{version}-%{release}
Requires: Paste-python3 = %{version}-%{release}
Requires: python-openid
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : pytest-runner
BuildRequires : python-openid
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
*Paste is in maintenance mode and recently moved from bitbucket to github.
Patches are accepted to keep it on life support, but for the most part, please
consider using other options.*

%package license
Summary: license components for the Paste package.
Group: Default

%description license
license components for the Paste package.


%package python
Summary: python components for the Paste package.
Group: Default
Requires: Paste-python3 = %{version}-%{release}
Provides: paste-python

%description python
python components for the Paste package.


%package python3
Summary: python3 components for the Paste package.
Group: Default
Requires: python3-core

%description python3
python3 components for the Paste package.


%prep
%setup -q -n Paste-3.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571066554
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Paste
cp %{_builddir}/Paste-3.2.2/docs/license.txt %{buildroot}/usr/share/package-licenses/Paste/391729571488896efa70494919f96aab67116ad1
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Paste/391729571488896efa70494919f96aab67116ad1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
